version: '3.1'

services:
  customsurveytelegrambot:
    depends_on:
      - cstb-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  cstb-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'cstb_db'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'dev_csb_db_user'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'dev_csb_db_password'

    ports:
      - '5432:5432'
    expose:
      - '5432'
